### PR TITLE
On page handler

### LINKED ISSUE #8: No way to get text of the entire page
I'm trying to get the page title and body text to cache for local searching. However, using `html`, `body`, etc. don't allow me to get the text of the entire page. I can use `title` as a selector to get the page title, but if I can't get the body text at the same time, I can't easily save those together into my local cache (I'd like to use a `(title, body)` tuple for saving them). Is there something I'm missing here? Would resolving this be in-scope for crabler?

If I'm thinking about implementing it, I was thinking of a new `on_page` handler that would provide the entire page in one request that would compliment the existing `on_html` handler. Would that be in scope for this library?

### PR DESCRIPTION
**Pull request by Susurrus**
Add a handler for getting the entire page text.

Closes #8.

### CODE REVIEW

**Comment by Gonzih** [comment]
Good stuff!!

**Comment by Gonzih** [comment]
I merged your changes in, but make test is failing now, can you please take a look? I think i now enabled CI on all PRs, but lets see if it actually works. Not sure why it wasnt running anything prior to this.

**Comment by Susurrus** [comment]
This is because the `crabler_derive` pulled in by `crabler` during tests isn't using the new changes I made so doesn't understand `on_page`. Using the local copy fixes this, so this should be resolved once you make a new `crabler_derive` release:
```
diff --git a/Cargo.toml b/Cargo.toml
index 4a0056a..9f54cbe 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -25,8 +25,8 @@ async-trait = "0.1.52"
 thiserror = "1.0"
 log = { version = "0.4.14", features = ["kv_unstable"] }
 femme = "2.1.1"
-crabler_derive = "0.1.7"
-# crabler_derive = { path = "./crabler_derive" }
+# crabler_derive = "0.1.7"
+crabler_derive = { path = "./crabler_derive" }
 crabquery = "0.1.8"
 # crabquery = { path = "/home/gnzh/mydev/crabquery" }
```

**Comment by Gonzih** [comment]
Oh, my bad, lemmy fix this.

**Comment by Gonzih** [comment]
Just published the latest version, great job! Thanks a lot for this!

**Pull request merged**
