### PR TITLE
Minor style fixes

### PR DESCRIPTION
**Pull request by Susurrus**
Found by `rustfmt` and `clippy`

### CODE REVIEW

**Comment by Gonzih** [comment]
Trying to figure out why CI isnt running. @Susurrus can you try and enable github actions on your forked repository?

**Comment by Susurrus** [comment]
Actions were already on by default for my repo

**Comment by Gonzih** [comment]
I dont see them running in your repo on main or on lints branch, try rebasing. I did some changes to CI configuration not so long ago, maybe that is the issue.

**Comment by Susurrus** [comment]
I just amended my commit and force pushed. I'm not seeing anything change here tho.

**Comment by Gonzih** [comment]
For some reason your actions are empty https://github.com/Susurrus/crabler/actions
Ammend would not do much, you need to do `git rebase origin:main` I think

**Comment by Susurrus** [comment]
Rebased. It looked like it was running the tests, but it's back to the same state it was in previously. I've never set up Github Actions, so not certain what's going on.

**Comment by Gonzih** [comment]
Meged this as is for now, dunno why PR integrations arent working. Weirdest thing ever.

**Pull request merged**
